language: php

php:
- 7.3

before_install:
  - phpenv config-rm xdebug.ini
  - pecl install -f pcov

install:
- composer install --no-interaction --no-suggest


script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover